### ISSUE TITLE
Neaprašyti kintamieji server.py

### ISSUE THREAD

**Issue by Justas-Kaulakis** [justinas2314/Tamo-API#1]
server.py faile yra neparašytų kintamųjų.
ką su jais daryt??
![image](https://user-images.githubusercontent.com/63920269/161109294-16e5253c-5369-48a0-8e55-ec28cce13e98.png)

Taip pat man atrodo galima padaryt \__init\__.py ir programuojančiam naudot koda kaip 'package'.
pvz.: from TamoAPI import TamoSession

**Comment by Justas-Kaulakis** [comment]
Beje žiauriai kietas API

**Comment by justinas2314** [comment]
FAILED_LOGINS, jeigu atsimenu teisingai, buvo dalis feature, dėl kurio vėliau persigalvojau, ir būtent šias kelias eilutes pamiršau ištrinti. Rytoj, kai turėsiu laiko pataisysiu šitą bug.

**Comment by justinas2314** [comment]
Dėl init ir patogesnio importavimo tai nelabai pasidomėjau kaip implementuoti, bet idėja gera. Irgi rytoj galėsiu dėl to pažiūrėti.

Dar didelis ačiū už feedback, nes būčiau šito bug taip ir nepastebėjęs.
