### ISSUE TITLE
Tamo pakeistas stilius, Namų darbai neveikia, vidurkis returning 200 code

### ISSUE THREAD

**Issue by xxbn2x** [justinas2314/Tamo-API#6]
Šiandien Tamo pakeitė stilių ant svetainės ir scraperio dalys neveikia. Testavau tik namų darbų ir vidurkio funkcijos. Namų darbai išmeta problemas, nes negali rasti "span". O vidurkis atiduoda code 200, galima problema su prisijungimu. Rytoj turėsiu laiko ir pažvelgsiu giliau.

**Comment by justinas2314** [comment]
Man pavyko gauti vienos tamo paskyros prisijungimo duomenis (ne mokinio, bet galvoju turėtų maždaug būti tas pats) ir artimuoju metu pabandysiu pats pasižiūrėti, kas atsitiko.

**Comment by xxbn2x** [comment]
Džiugu matyti, kad dar esate ant projekto. Aš pats jau bandau taisyti viską. Namu_darbus pataisiau, viskas atrodo veikia išskyrus failus prisegtus (juos į kitą div įmetė). Į kitus dalykus dar nežiūrėjau. Rytoj tikiuosis pataisysiu prisegtu failų problemą ir pažiūrėsiu kas dar neveikia. Galiu jums atsiųsti kai kurių html puslapiu jeigu reikia.

**Comment by justinas2314** [comment]
Bent kol kas man nereikia html failų, džiaugiuosi, kad aktyviai taisote, kas neveikia. Būčiau dėkingas, jeigu bedirbdami įkeltumėte fix'us, kad vėliau nereikėtų sėsti prie kodo, kuris jau vieną kartą buvo pataisytas.

**Comment by xxbn2x** [comment]
Pataisiau ir man rods pas mane pilnai veikia (seniau neveikė):
Namu_darbai()
Pusmeciai()

Netikrinau 100% ar rezultatai teisingi, bet iš pirmo žvilgsnio atrodo, kad teisingi. Rytoj dar pataisysiu kitas funkcijas ir pull reqeustą atsiųsiu, kad peržiūrėtume.

**Comment by xxbn2x** [comment]
As pataisiau daug ko, bet noriu tik pakesisti scraper.py ir nezinau kaip tai padaryti. Pagelbekite prasau. Nenoriu daryti pull reqeust, nes ten ir testavimo mano failas kuris jum nereiklaingas ir __pycache__ pakeistas, nezinau kam jis.

**Comment by justinas2314** [comment]
Galite atsiųsti failą ar jo turinį per staskevicius14@gmail.com, toliau pats (turbūt šiek tiek paredaguotą) kodą įkelčiau į main branchą.

**Comment by xxbn2x** [comment]
Rytoj atsiųsiu.

**Comment by justinas2314** [comment]
Ačiū už pagalbą, dar padariau šiek tiek testavimo atrodo viskas dabar turėtų veikti. Kai netingėsiu (turbūt iki pirmadienio) pataisysiu ir async API versiją.
